Flortex.Inventory/Controllers/MastersController.cs
using MAP.Inventory.Interface;
using MAP.Inventory.Logging;
using MAP.Inventory.Model;
using MAP.Inventory.ModelImple;
using MAP.Inventory.Web.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MAP.Inventory.Web.Controllers
{

    public class MastersController : Controller
    {

        #region Product Masters



        [SessionExpire(FeatureKey = "ProductsCategoryLandingPage", RequestType = 1)]
        public ActionResult ProductsCategoryList()
        {
            PLog.Info("BEGIN::Controller > Home, Method > ProductCategoryList()");
            try
            {
                var str = LoadProductsCategory();
                ViewBag.Data = str;
            }
            catch (Exception ex)
            {
                PLog.Error("Error::Controller > Home, Method > ProductCategoryList()", ex);
            }
            PLog.Info("END::Controller > Home, Method > ProductCategoryList()");
            return View();
        }

        [SessionExpire(FeatureKey = "ProductsCategoryLandingPage", RequestType = 1)]
        public string LoadProductsCategory()
        {
            PLog.Info("BEGIN::Controller > Home, Method > LoadProductsCategory()");

            System.Web.Script.Serialization.JavaScriptSerializer serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            List<Dictionary<string, object>> rows = new List<Dictionary<string, object>>();
            try
            {

                IProductsCategoryImple oProducts = new ProductsCategoryImple();

                DataTable dt = oProducts.GetGridData(0); //0 will gets all the products data


                Dictionary<string, object> row;
                foreach (DataRow dr in dt.Rows)
                {
                    row = new Dictionary<string, object>();
                    foreach (DataColumn col in dt.Columns)
                    {
                        row.Add(col.ColumnName, dr[col]);
                    }
                    rows.Add(row);
                }
            }
            catch (Exception ex)
            {
                PLog.Error("Error::Controller > Home, Method > LoadProductsCategory()", ex);
            }
            PLog.Info("END::Controller > Home, Method > LoadProductsCategory()");
            return serializer.Serialize(rows);
        }

        [SessionExpire(FeatureKey = "AddProductsCategory", RequestType = 1)]
        public ActionResult ProductsCategory()
        {
            PLog.Info("BEGIN::Controller > Home, Method > ProductsCategory");
            PLog.Info("END::Controller > Home, Method >ProductsCategory");
            return View(new ProductsCategoryModel());
        }


        [SessionExpire(FeatureKey = "SaveProductCategory", RequestType = 2)]
        public ActionResult SaveProductsCategory(string Data)
        {
            PLog.Info("BEGIN::Controller > Home, Method > SaveProductsCategory(string Data)");
            long flg = 0;
            try
            {
                ProductsCategoryModel obj = JsonConvert.DeserializeObject<ProductsCategoryModel>(Data);
                IProductsCategoryImple oProducts = new ProductsCategoryImple();
                flg = oProducts.SaveProductCategory(obj);
            }
            catch (Exception ex)
            {
                PLog.Error("Error::Controller > Home, Method > SaveProductsCategory(string Data)", ex);
            }
            PLog.Info("END::Controller > Home, Method > SaveProductsCategory(string Data)");
            return Content(flg.ToString());
        }

        [SessionExpire(FeatureKey = "EditProductsCategory", RequestType = 1)]
        public ActionResult UpdateProductsCategory(string ID)
        {
            PLog.Info("BEGIN::Controller > Home, Method > UpdateProductsCategory(string ID");
            ProductsCategoryModel objModel = null;
            IProductsCategoryImple oProducts = new ProductsCategoryImple();
            try
            {

                if (!string.IsNullOrEmpty(ID))
                {
                    objModel = oProducts.EditProdcutCategory(Convert.ToInt32(ID));
                }
            }
            catch (Exception ex)
            {
                PLog.Error("Error::Controller > Home, Method > UpdateProductsCategory(string ID)", ex);
            }
            PLog.Info("END::Controller > Home, Method > UpdateProductsCategory(string ID)");
            return View($"ProductsCategory", objModel);
        }

        [SessionExpire(FeatureKey = "DeleteProductsCategory", RequestType = 2)]
        public long DeleteProductsCategory(string ID)
        {
            PLog.Info("BEGIN::Controller > Home, Method > DeleteProductsCategory(string ID)");
            long ret = 0;
            if (!string.IsNullOrEmpty(ID))
            {
                try
                {
                    IProductsCategoryImple oProducts = new ProductsCategoryImple();
                    ret = oProducts.DeleteProductsCategory(Convert.ToInt32(ID));
                }
                catch (Exception ex)
                {
                    PLog.Error("Error::Controller > Home, Method > DeleteProductsCategory(string ID)", ex);
                }
            }
            PLog.Info("END::Controller > Home, Method > DeleteProductsCategory(string ID)");
            return ret;
        }


        [SessionExpire(FeatureKey = "ProductsLanding", RequestType = 1)]
        public ActionResult ProductsList()
        {
            PLog.Info("BEGIN::Controller > Home, Method > ProductsList()");

            try
            {
                var str = LoadProducts();
                ViewBag.Data = str;
            }
            catch (Exception ex)
            {
                PLog.Error("Error::Controller > Home, Method > ProductsList()", ex);
            }
            PLog.Info("END::Controller > Home, Method > ProductsList()");
            return View();
        }

        [SessionExpire(FeatureKey = "ProductsLanding", RequestType = 1)]
        public string LoadProducts()
        {
            PLog.Info("BEGIN::Controller > Home, Method > LoadProducts()");

            System.Web.Script.Serialization.JavaScriptSerializer serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            List<Dictionary<string, object>> rows = new List<Dictionary<string, object>>();
            try
            {

                IProductsImple oProductsImple = new ProductsImple();

                DataTable dt = oProductsImple.GetGridData(0); //0 will gets all the products data


                Dictionary<string, object> row;
                foreach (DataRow dr in dt.Rows)
                {
                    row = new Dictionary<string, object>();
                    foreach (DataColumn col in dt.Columns)
                    {
                        row.Add(col.ColumnName, dr[col]);
                    }
                    rows.Add(row);
                }
            }
            catch (Exception ex)
            {
                PLog.Error("Error::Controller > Home, Method > LoadProducts()", ex);
            }
            PLog.Info("END::Controller > Home, Method > LoadProducts()");
            return serializer.Serialize(rows);
        }

        [SessionExpire(FeatureKey = "AddProducts", RequestType = 1)]
        public ActionResult Products()
        {
            PLog.Info("BEGIN::Controller > Home, Method > ChangePasswordView");
            PLog.Info("END::Controller > Home, Method >ChangePasswordView");
            return View(new ProductsModel());
        }

        [SessionExpire(FeatureKey = "SaveProduct", RequestType = 2)]
        public ActionResult SaveProduct(string Data)
        {
            PLog.Info("BEGIN::Controller > Home, Method > SaveProduct(string Data)");
            long flg = 0;
            IProductsImple oProductsImple = new ProductsImple();
            try
            {
                ProductsModel obj = JsonConvert.DeserializeObject<ProductsModel>(Data);
                string[] date = obj.efDate.Split('-');
                obj.efDate = new DateTime(Convert.ToInt32(date[2]), Convert.ToInt32(date[1]), Convert.ToInt32(date[0])).ToString();
                flg = oProductsImple.SaveProducts(obj);
            }
            catch (Exception ex)
            {
                PLog.Error("Error::Controller > Home, Method > SaveProduct(string Data)", ex);
            }
            PLog.Info("END::Controller > Home, Method > SaveProduct(string Data)");
            return Content(flg.ToString());
        }

        [SessionExpire(FeatureKey = "EditProducts", RequestType = 1)]
        public ActionResult UpdateProduct(string ID)
        {
            PLog.Info("BEGIN::Controller > Home, Method > UpdateProduct(string ID");
            IProductsImple oProductsImple = new ProductsImple();
            ProductsModel objModel = null;
            try
            {

                if (!string.IsNullOrEmpty(ID))
                {
                    objModel = oProductsImple.EditProdcut(Convert.ToInt32(ID));
                }
            }
            catch (Exception ex)
            {
                PLog.Error("Error::Controller > Home, Method > UpdateProduct(string ID)", ex);
            }
            PLog.Info("END::Controller > Home, Method > UpdateProduct(string ID)");
            return View("Products", objModel);
        }

        [SessionExpire(FeatureKey = "DeleteProducts", RequestType = 2)]
        public long DeleteProduct(string ID)
        {
            PLog.Info("BEGIN::Controller > Home, Method > DeleteProduct(string ID)");
            long ret = 0;
            if (!string.IsNullOrEmpty(ID))
            {
                try
                {
                    IProductsImple oProductsImple = new ProductsImple();
                    ret = oProductsImple.DeleteProduct(Convert.ToInt32(ID));
                }
                catch (Exception ex)

Flortex.Inventory/Views/Masters/CustomersList.cshtml
@using MAP.Inventory.Model;
@{
    string Data = "[]";

    if (ViewBag.Data != "")
    {
        Data = ViewBag.Data;
    }

    SessionManager objSession = null;
    if (Session["SessionManager"] != null)
    {
        objSession = (SessionManager)Session["SessionManager"];
    }
}

<form class="cmxform" role="search">
    <div class="row-fluid heading">
        <div class="span12">
            <h2>List of Customers</h2>
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-lg-12 span12">
            <div id="grid"></div>
        </div>
    </div>
</form>

<script id="template" type="text/x-kendo-template">
    @if (objSession.RoleFeatures != null && objSession.RoleFeatures.ContainsKey("AddCustomers") && objSession.RoleFeatures["AddCustomers"])
    {
        <a class="k-button" onclick="return toolbar_click()">ADD NEW CUSTOMER</a>
    }
</script>

<script type="text/javascript">

    var Documents = @Html.Raw(Data)
    $(document).ready(function () {

        // Documents = getDocs();
        function getDocs() {
            $.ajax({
                url: '/Masters/Getcustomers',
                type: 'Get',
                async: false,
                success: function (res) {
                    Documents = JSON.parse(res);
                },
                error: function (e) { customAlert('error occured.', 'alert'); }
            });
            return Documents;
        }

        var dataSource = new kendo.data.DataSource({
            //pageSize: 8,
            data: Documents,
            autoSync: true,
            schema: {
                model: {
                    fields: {
                        NodeNo: { editable: false },
                        FirstName: { type: "string", editable: false },
                        LastName: { type: "string", editable: false },
                        Mobile: { type: "string", editable: false },
                    }
                }
            }
        });

        function gridDataBound(e) {
            var grid = e.sender;
            if (grid.dataSource.total() == 0) {
                var colCount = grid.columns.length;
                $(e.sender.wrapper)
                    .find('tbody')
                    .append('<tr class="kendo-data-row"><td colspan="' + colCount + '" class="no-data">No Data :( <br/>Add new <b>Warehouse<b></td></tr>');
            }
        };

        $("#grid").kendoGrid({
            dataSource: dataSource,
            pageable: false,
            //pageSize: 8,
            height: 500,
            sortable: true,
            filterable: true,
            toolbar: [
     { template: kendo.template($("#template").html()) }
            ],
            columns: [
                // { field: "id", title: "Doc No", width: "100px" },
                { field: "FirstName", title: "First Name", width: "130px" },
                { field: "LastName", title: "Last Name", width: "130px" },
                 { field: "Mobile", title: "Mobile", width: "130px" }
                  @if (objSession.RoleFeatures != null && objSession.RoleFeatures.ContainsKey("EditCustomers") && objSession.RoleFeatures["EditCustomers"])
                  {
                        <text>, { command: { text: "Edit", name: "edit", click: onEdit }, title: " ", width: "100px" } </text>
                  }

                   @if (objSession.RoleFeatures != null && objSession.RoleFeatures.ContainsKey("DeleteCustomers") && objSession.RoleFeatures["DeleteCustomers"])
                   {
               <text>, {
                       command: {
                           name: "Delete ", click: function (e) {
                               e.preventDefault();
                               var self = this;

                               smoke.confirm("Are you sure, Do you want to delete.?", function (ev) {
                                   if (ev) {
                                       var tr = $(e.target).closest("tr");
                                       var data = self.dataItem(tr);
                                       $.ajax({
                                           url: '/Masters/DeleteCustomer',
                                           type: 'POST',
                                           data: { "ID": data.NodeNo },
                                           beforeSend: function () {
                                               $("#ajaxLoadingImg").show();
                                           },
                                           complete: function () { $("#ajaxLoadingImg").hide(); },
                                           success: function (res) {
                                               if (res > 0) {
                                                   customAlert('Deleted Successfully.', 'alert');
                                                   Documents = getDocs();
                                                   var dataSource = new kendo.data.DataSource({ data: Documents });
                                                   var grid = $('#grid').data("kendoGrid");
                                                   dataSource.read();
                                                   grid.setDataSource(dataSource);
                                               }
                                           },
                                           error: function (e) { customAlert('error occured.', 'alert'); }
                                       });//end ajax
                                   }
                               }, {
                                   ok: "Yep",
                                   cancel: "Nope",
                                   classname: "custom-class",
                                   reverseButtons: true
                               });
                           }

                       }, title: " ", width: "100px"
                   }</text>
                       }
            ],
            editable: true,
            filterable: {
                extra: false, //do not show extra filters
                operators: { // redefine the string operators
                    string: {
                        contains: "Contains",
                        startswith: "Starts With",
                        eq: "Is Equal To"
                    }
                }
            },
            dataBound: gridDataBound
        });
    });
    Mousetrap.bind(['ctrl+a'], function (e) {
        e.preventDefault();
        toolbar_click();
    });

    function toolbar_click() {
        window.location.href = '/Masters/AddCustomer';
    }

    function onEdit(e) {
        e.preventDefault();
        var tr = $(e.target).closest("tr");
        var data = this.dataItem(tr);
        window.location.href = "/Masters/UpdateCustomer?ID=" + data.NodeNo;
    }


</script>

Flortex.Inventory/Views/Masters/ProductsCategory.cshtml
@model MAP.Inventory.Model.ProductsCategoryModel
@using MAP.Inventory.Model;
@{
    ViewBag.Title = "ProductsCategory";
    SessionManager objSession = null;
    if (Session["SessionManager"] != null)
    {
        objSession = (SessionManager)Session["SessionManager"];
    }
}
<form role="search" id="frmProducts" class="cmxform">

    @if (Model.ProductCategoryID > 0)
    {
        <div class="row-fluid heading">
            <div class="span12">
                <h2>Edit Product Category</h2>
            </div>
        </div>
    }
    else
    {
        <div class="row-fluid heading">
            <div class="span12">
                <h2>Add Product Category</h2>
            </div>
        </div>
    }


    @Html.HiddenFor(m => m.ProductCategoryID)

    <div class="row-fluid">
        <div class="span2">
            <label for="txtName" class="label1">Product Name</label>
        </div>
        <div class="span8">
            <input type="text" class="form-control mousetrap" style="width: 300px" name="txtName" id="txtName" placeholder="Product name" value="@Model.Name">
        </div>
    </div>

    <div class="row-fluid">
        <div class="span2">
        </div>
        <div class="span8">
            @if (objSession.RoleFeatures != null && objSession.RoleFeatures.ContainsKey("SaveProductCategory") && objSession.RoleFeatures["SaveProductCategory"])
            {
                <button type="submit" class="btn btn-default" id="btnSaveProduct">
                    Save
                </button>
            }

            @if (objSession.RoleFeatures != null && objSession.RoleFeatures.ContainsKey("ClearProductCategory") && objSession.RoleFeatures["ClearProductCategory"])
            {

                <button class="btn btn-default" id="btnClear">Reset</button>
            }
            @if (objSession.RoleFeatures != null && objSession.RoleFeatures.ContainsKey("CancelProductCategory") && objSession.RoleFeatures["CancelProductCategory"])
            {
                <a class="btn btn-default" href="@Url.Action("Index", "Home")">Cancel</a>
            }
        </div>

    </div>

</form>



<script type="text/javascript">


    $(function () {



        var createProduct = function () {
            var obj = {
                ProductCategoryID: $("#ProductCategoryID").val(),
                Name: $("#txtName").val()
            }
            return JSON.stringify(obj);
        }

        var _saveProducts = function () {
            if ($("#frmProducts").valid()) {
                $.ajax({
                    url: '/Masters/SaveProductsCategory',
                    type: 'post',
                    data: { "Data": createProduct() },
                    beforeSend: function () {
                        $("#ajaxLoadingImg").show();

                    },
                    complete: function () { $("#ajaxLoadingImg").hide(); },
                    success: function (data) {
                        if (data > 0) {
                            if ($("#ProductCategoryID").val() > 0)
                                customAlert('Updated Successfully', 'alert', function () { $("#txtName").focus(); });
                            else
                                customAlert('Created Successfully', 'alert', function () { $("#txtName").focus(); });
                            clearContorls();
                        }
                        else {
                            customAlert('Error occured', 'alert');
                        }
                    },

                    error: function (e) {
                        debugger
                        customAlert('Error occured', 'alert');
                    }
                });
            }
        };

        $("#btnSaveProduct").on("click", function (e) {
            e.preventDefault();
            _saveProducts();
        });

        $("#frmProducts").validate({
            rules: {
                txtName: "required"
            },
            messages: {
                txtName: "please enter product name"

            }
        });

        $("#btnClear").on("click", function (e) {
            e.preventDefault();
            clearContorls();
        });

        var clearContorls = function () {
            $("#ProductCategoryID").val('0');
            $("#txtName").val('');

            $("#txtName").focus();
        };


        Mousetrap.bind(['ctrl+s', 'command+s'], function (e) {
            e.preventDefault();
            _saveProducts();
        });

        Mousetrap.bind(['ctrl+r', 'command+r'], function (e) {
            e.preventDefault();
            clearContorls();
        });

        Mousetrap.bind(['ctrl+h', 'command+h'], function (e) {
            e.preventDefault();
            window.location.href = '@Url.Action("Index", "Home")';
        });

        Mousetrap.bind(['ctrl+backspace', 'command+backspace'], function (e) {
            e.preventDefault();
            window.location.href = '@Url.Action("ProductsCategoryList", "Masters")';
        });

        Mousetrap.bind(['ctrl+r', 'command+r'], function (e) {
            e.preventDefault();
            clearContorls();
        });

        $("#txtName").focus();
    });

</script>

Flortex.Inventory/Views/Masters/Warehouse.cshtml
@model MAP.Inventory.Model.WareHouseModel
@using MAP.Inventory.Model;
@using System.Data;
@using MAP.Inventory.ModelImple;
@{
    ViewBag.Title = "Warehouse";
    LookUps _LookUps = new LookUps();
    DataTable dtStatus = _LookUps.GetLookUps(1);// look up id for status=1
    SessionManager objSession = null;
    if (Session["SessionManager"] != null)
    {
        objSession = (SessionManager)Session["SessionManager"];
    }

}

<form role="search" id="frmWareHouse" class="cmxform">

    @if (Model.WareHouseID > 0)
    {
        <div class="row-fluid heading">
            <div class="span12">
                <h2>Edit Warehouse</h2>
            </div>
        </div>
    }
    else
    {
        <div class="row-fluid heading">
            <div class="span12">
                <h2>Add Warehouse</h2>
            </div>
        </div>
    }

    @Html.HiddenFor(m => m.WareHouseID);

    <div class="row-fluid">
        <div class="span2">
            <label for="txtCode" class="label1">Warehouse Code</label>
        </div>
        <div class="span8">
            <input type="text" class="form-control mousetrap" style="width: 250px" name="txtCode" id="txtCode" placeholder="Warehouse Code" value="@Model.Code">
        </div>
    </div>

    <div class="row-fluid">
        <div class="span2">
            <label for="txtName" class="label1">Warehouse Name</label>
        </div>
        <div class="span8">
            <input type="text" class="form-control mousetrap" style="width: 250px" name="txtName" id="txtName" placeholder="Warehouse Name" value="@Model.Name">
        </div>
    </div>

    <div class="row-fluid">
        <div class="span2">
            <label class="label1" for="drpStatus">Status</label>
        </div>
        <div class="span8">
            <select class="form-control mousetrap" style="width: 250px" name="drpStatus" id="drpStatus">
                @if (dtStatus != null && dtStatus.Rows.Count > 0)
                {
                    for (int i = 0; i < dtStatus.Rows.Count; i++)
                    {
                        if (Model.Status != 0 && Model.Status == Convert.ToInt32(dtStatus.Rows[i]["NodeNo"].ToString()))
                        {
                            <option selected="selected" value="@dtStatus.Rows[i]["NodeNo"].ToString()">@dtStatus.Rows[i]["Name"].ToString()</option>
                        }
                        else
                        {
                            <option value="@dtStatus.Rows[i]["NodeNo"].ToString()">@dtStatus.Rows[i]["Name"].ToString()</option>
                        }
                    }
                }
            </select>
        </div>
    </div>

    <div class="row-fluid" style="display: none" id="divEffectiveDate">
        <div class="span2">
            <label class="label1" for="dtEDate">Effective Date</label>
        </div>
        <div class="span8">
            <input placeholder="Effective Date" name="dtEDate" id="dtEDate">
            <
        </div>
    </div>

    <div class="row-fluid">
        <div class="span2">
        </div>
        <div class="span8">
            @if (objSession.RoleFeatures != null && objSession.RoleFeatures.ContainsKey("SaveWarehouse") && objSession.RoleFeatures["SaveWarehouse"])
            {
                <button type="submit" class="btn btn-default" id="btnSaveWarehouse">
                    Save
                </button>
            }

            @if (objSession.RoleFeatures != null && objSession.RoleFeatures.ContainsKey("ClearWarehouse") && objSession.RoleFeatures["ClearWarehouse"])
            {

                <button class="btn btn-default" id="btnClear">Reset</button>
            }

            @if (objSession.RoleFeatures != null && objSession.RoleFeatures.ContainsKey("CancelWarehouse") && objSession.RoleFeatures["CancelWarehouse"])
            {
                <a class="btn btn-default" href="@Url.Action("Index", "Home")">Cancel</a>
            }
        </div>

    </div>

</form>

<script type="text/javascript">
    $(function () {
        var EndDate = '';
        $("#dtEDate").kendoDatePicker({ format: "dd-MM-yyyy" });
        $("#dtEDate").val(getDate());

        function getDate() {
            var date = new Date();
            return date.getDate() + "-" + parseInt(date.getMonth() + 1) + "-" + date.getFullYear()
        }

        $(".k-datepicker").css("width", "250px");

        $("#drpStatus").on("change", function (e) {
            var selected = $(this).val();
            EndDate = $("#dtEDate").val();
            if (selected == "2") {
                $("#divEffectiveDate").slideDown();
            }
            else {
                $("#divEffectiveDate").slideUp();
            }
        });

        var createWarehouse = function () {
            var obj = {
                WareHouseID: $("#WareHouseID").val(),
                Code: $("#txtCode").val(),
                Name: $("#txtName").val(),
                Status: $("#drpStatus option:selected").val(),
                efDate: $("#dtEDate").val()
            }
            return JSON.stringify(obj);
        }


        $("#btnSaveWarehouse").on("click", function (e) {
            e.preventDefault();
            _saveWareHouse();
        });

        var _saveWareHouse = function () {
            if ($("#frmWareHouse").valid()) {
                $.ajax({
                    url: '/Masters/SaveWarehouse',
                    type: 'post',
                    data: { "Data": createWarehouse() },
                    beforeSend: function () {
                        $("#ajaxLoadingImg").show();

                    },
                    success: function (data) {
                        if (data > 0) {

                            if ($("#WareHouseID").val() > 0)
                                customAlert('Updated Successfully', 'alert', function () { $("#txtCode").focus(); });
                            else
                                customAlert('Created Successfully.', 'alert', function () { $("#txtCode").focus(); });

                            clearContorls();
                        }
                        else {
                            customAlert('Error occured', 'alert');
                        }
                    },
                    complete: function () { $("#ajaxLoadingImg").hide(); },
                    error: function (e) { customAlert('Error occured', 'alert'); }
                });
            }
        }

        $("#frmWareHouse").validate({
            rules: {
                txtCode: "required",
                txtName: "required",
                drpStatus: {
                    required: true,
                    greaterThanZero: true
                },
            },
            messages: {
                txtCode: "please enter warehouse code",
                txtName: "please enter warehouse name",
                drpStatus: "please select status."

            }
        });

        $("#btnClear").on("click", function (e) {
            e.preventDefault();
            clearContorls();
            $('#txtCode').focus();
        });

        var clearContorls = function () {
            $("#WareHouseID").val('0');
            $("#txtCode").val('');
            $("#txtName").val('');
            $("#drpStatus").val('1');
            $("#dtEDate").val(getDate());
            $("#drpStatus").change();
            $('#txtCode').focus();
        };
        if ('@Model.WareHouseID' > 0) {
            $("#drpStatus").change();
            $("#dtEDate").val('@Model.efDate');
        }

        Mousetrap.bind(['ctrl+s', 'command+s'], function (e) {
            e.preventDefault();
            _saveWareHouse();
        });

        Mousetrap.bind(['ctrl+backspace', 'command+backspace'], function (e) {
            e.preventDefault();
            window.location.href = '@Url.Action("Warehouses", "Masters")';
        });


        Mousetrap.bind(['ctrl+r', 'command+r'], function (e) {
            e.preventDefault();
            clearContorls();
        });

        Mousetrap.bind(['ctrl+h', 'command+h'], function (e) {
            e.preventDefault();
            window.location.href = '@Url.Action("Index", "Home")';
        });

        $('#txtCode').focus();

    });


</script>